# Generated by Django 4.0.5 on 2023-04-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='lowTitle',
        ),
    ]
