# Generated by Django 4.0.5 on 2023-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_images_lowtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='868x655'),
        ),
    ]
