# Generated by Django 4.0.5 on 2023-04-30 21:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='two',
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
